/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sq008aZtq35
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Switch } from "@/components/ui/switch"

export function brothers() {
  return (
    <div className="bg-white p-6">
      <h1 className="text-xl font-bold mb-4">Privacy settings</h1>
      <div className="divide-y divide-gray-200">
        <div className="py-4">
          <h2 className="text-lg font-semibold mb-3">Profile data</h2>
          <div className="grid grid-cols-3 gap-4">
            <div className="flex justify-between">
              <span>Profile picture:</span>
              <Switch defaultChecked id="profile-picture-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Follower list:</span>
              <Switch defaultChecked id="follower-list-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Follow list:</span>
              <Switch defaultChecked id="follow-list-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="profile-picture-followers" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="follower-list-followers" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="follow-list-followers" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="profile-picture-none" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="follower-list-none" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="follow-list-none" />
            </div>
            <div className="flex justify-between">
              <span>Bio :</span>
              <Switch defaultChecked id="bio-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Blog Category member info:</span>
              <Switch defaultChecked id="blog-category-member-info-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="bio-followers" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="blog-category-member-info-followers" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="bio-none" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="blog-category-member-info-none" />
            </div>
          </div>
        </div>
        <div className="py-4">
          <h2 className="text-lg font-semibold mb-3">Public data</h2>
          <div className="grid grid-cols-3 gap-4">
            <div className="flex justify-between">
              <span>Blog category follow info</span>
              <Switch defaultChecked id="blog-category-follow-info-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Blog category member info:</span>
              <Switch defaultChecked id="blog-category-member-info-everyone2" />
            </div>
            <div className="flex justify-between">
              <span>Public Follow list:</span>
              <Switch defaultChecked id="public-follow-list-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="blog-category-follow-info-followers" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="blog-category-member-info-followers2" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="public-follow-list-followers" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="blog-category-follow-info-none" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="blog-category-member-info-none2" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="public-follow-list-none" />
            </div>
            <div className="flex justify-between">
              <span>Department member info</span>
              <Switch defaultChecked id="department-member-info-everyone" />
            </div>
            <div className="flex justify-between">
              <span>Followers</span>
              <Switch id="department-member-info-followers" />
            </div>
            <div className="flex justify-between">
              <span>None</span>
              <Switch id="department-member-info-none" />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
